### PR TITLE
Changed PySplunkWhisperer2_local.py from python2 to python3

### PR DESCRIPTION
**Pull request by Sad-theFaceless**

### CODE REVIEW

**Comment by cnotin** [comment]
Thanks for the suggestion! Could you check if it's still compatible with PyInstaller as used in https://github.com/cnotin/SplunkWhisperer2/blob/master/PySplunkWhisperer2/build_exe.bat?

**Comment by cnotin** [comment]
It also depends on which Python version is available on the machine where the forwarder is running locally. Could be both, so perhaps we could have two files to cover both cases

**Comment by Sad-theFaceless** [comment]
Hello! No issue with `build_exe.bat` :
image

Yes I agree, having both files seems better.

**Comment by cnotin** [comment]
Thanks for your help and taking the time to check. I prefer to keep the python2 files as the default so no one is surprised but thank you very much for adding python3 variants!

**Pull request merged**
